name: master

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Build
        run: |
          cd ~/build/koodibril
          git checkout staging
          git pull
          ./mvnw -Pprod -DskipTests -T 4 verify jib:dockerBuild
          docker image tag koodibril koodibril:master
      - name: Deploy
        run: |
          cd ~/websites/koodibril
          docker-compose up -d
